name: data_visualizer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  file_picker: ^8.3.2
  csv: ^6.0.0
  fl_chart: ^0.63.0
  google_fonts: ^6.2.1
  pdf: ^3.11.3
  screenshot: ^3.0.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^11.0.0
  path_provider: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
